package views;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LLira
 */
public class frmMain extends javax.swing.JFrame {

    double[][] Matrix = null;
    int restrictions = 0, variables = 0, iter = 0, iteration = 0;
    Object array[] = null;
    Object LabelX[] = null, LabelY[] = null;
    
    // Tables
    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel modelSolution = new DefaultTableModel();

    /**
     * Creates new form main
     */
    public frmMain() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("Simplex method");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtVariable = new javax.swing.JTextField();
        txtRestriction = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSimplex = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSolution = new javax.swing.JButton();
        btnInteraction = new javax.swing.JButton();
        txtInteraction = new javax.swing.JTextField();
        btnClean = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFinal = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Maximization");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input data"));

        jLabel2.setText("Number of variables:");

        jLabel3.setText("Number of restrictions:");

        txtVariable.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVariable.setPreferredSize(new java.awt.Dimension(80, 30));

        txtRestriction.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRestriction.setPreferredSize(new java.awt.Dimension(80, 30));

        btnCalculate.setBackground(new java.awt.Color(0, 133, 207));
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("Calculate");
        btnCalculate.setPreferredSize(new java.awt.Dimension(80, 30));
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(txtRestriction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRestriction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/salir.png"))); // NOI18N
        btnSalir.setText("Quit");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Simplex table"));

        tblSimplex.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 153)));
        tblSimplex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "                X1", "                X2", "                X3", "                X4"
            }
        ));
        tblSimplex.setGridColor(new java.awt.Color(0, 0, 204));
        jScrollPane1.setViewportView(tblSimplex);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Enter the number of variables and constraints when you define the objective function to zero and the slack variables.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Problem solution");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnSolution.setBackground(new java.awt.Color(255, 255, 255));
        btnSolution.setText("Solution");
        btnSolution.setPreferredSize(new java.awt.Dimension(100, 30));
        btnSolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolutionActionPerformed(evt);
            }
        });
        jPanel4.add(btnSolution);

        btnInteraction.setBackground(new java.awt.Color(255, 255, 255));
        btnInteraction.setText("Interaction");
        btnInteraction.setPreferredSize(new java.awt.Dimension(100, 30));
        btnInteraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteractionActionPerformed(evt);
            }
        });
        jPanel4.add(btnInteraction);

        txtInteraction.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtInteraction.setForeground(new java.awt.Color(255, 51, 51));
        txtInteraction.setEnabled(false);
        txtInteraction.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel4.add(txtInteraction);

        btnClean.setBackground(new java.awt.Color(255, 255, 255));
        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/clean.png"))); // NOI18N
        btnClean.setText("Clean");
        btnClean.setPreferredSize(new java.awt.Dimension(100, 30));
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });
        jPanel4.add(btnClean);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Data output"));

        tblFinal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 153)));
        tblFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "                 S1", "                 S2", "                 S3", "                 S4"
            }
        ));
        tblFinal.setGridColor(new java.awt.Color(0, 0, 153));
        jScrollPane2.setViewportView(tblFinal);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        try {
            restrictions = Integer.parseInt(txtRestriction.getText());
            variables = Integer.parseInt(txtVariable.getText());

            model.setRowCount(restrictions + 1);
            model.setColumnCount(variables + restrictions + 2);
            array = new Object[variables + restrictions + 2];
            LabelX = new Object[variables + restrictions];
            for (int i = 1; i < array.length - 1; i++) {
                if (i < variables + 1) {
                    array[i] = "X" + i;
                    LabelX[i - 1] = "X" + i;
                } else {
                    array[i] = "S" + (i - variables);
                    LabelX[i - 1] = "S" + (i - variables);
                }
            }
            //---------------------
            LabelY = new Object[restrictions + 1];
            for (int i = 0; i < restrictions; i++) {
                model.setValueAt("R" + (i + 1), i, 0);
                LabelY[i] = "R" + (i + 1);
            }
            model.setValueAt("Z", restrictions, 0);
            LabelY[restrictions] = "Z";
            //----------------------
            array[array.length - 1] = "Result";
            model.setColumnIdentifiers(array);
            tblSimplex.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println(e.getClass());
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnSolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolutionActionPerformed
        // TODO add your handling code here:
        try {
            Matrix = new double[restrictions + 1][restrictions + variables + 1];
            for (int i = 0; i < (restrictions + 1); i++) {
                for (int j = 0; j < (restrictions + variables + 1); j++) {
                    Matrix[i][j] = Double.parseDouble(tblSimplex.getValueAt(i, j + 1).toString());
                }
            }
            while (checkResult() != true) {
                LabelY[rowPivot()] = LabelX[columnPivot()];
                newTable(rowPivot(), columnPivot());
                modelSolution.setColumnCount(restrictions + variables + 2);
                modelSolution.setRowCount(restrictions + 1);
                //--------------------------
                modelSolution.setColumnIdentifiers(array);
                //---------------------------
                for (int i = 0; i < (restrictions + 1); i++) {
                    modelSolution.setValueAt(LabelY[i], i, 0);
                    for (int j = 0; j < (restrictions + variables + 1); j++) {
                        modelSolution.setValueAt(Matrix[i][j], i, j + 1);
                    }
                }
                tblFinal.setModel(modelSolution);
                iteration++;
            }
            btnSolution.setEnabled(false);
            btnInteraction.setEnabled(true);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println(e.getClass());
        }
    }//GEN-LAST:event_btnSolutionActionPerformed

    private void btnInteractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteractionActionPerformed
        // TODO add your handling code here:
        try {
            Matrix = new double[restrictions + 1][restrictions + variables + 1];
            for (int i = 0; i < (restrictions + 1); i++) {
                for (int j = 0; j < (restrictions + variables + 1); j++) {
                    Matrix[i][j] = Double.parseDouble(tblSimplex.getValueAt(i, j + 1).toString());
                }
            }
            int k = 0;
            iter++;
            if (iter <= iteration) {
                txtInteraction.setText(": " + iter);
                while (iter > k) {
                    LabelY[rowPivot()] = LabelX[columnPivot()];
                    newTable(rowPivot(), columnPivot());
                    modelSolution.setColumnCount(restrictions + variables + 2);
                    modelSolution.setRowCount(restrictions + 1);
                    //--------------------------
                    modelSolution.setColumnIdentifiers(array);
                    //---------------------------
                    for (int i = 0; i < (restrictions + 1); i++) {
                        modelSolution.setValueAt(LabelY[i], i, 0);
                        for (int j = 0; j < (restrictions + variables + 1); j++) {
                            modelSolution.setValueAt(Matrix[i][j], i, j + 1);
                        }
                    }
                    tblFinal.setModel(modelSolution);
                    k++;
                }
            } else {
                iter = 0;
                iteration = 0;
                txtInteraction.setText("Final");
                btnSolution.setEnabled(true);
                btnInteraction.setEnabled(false);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println(e.getClass());
        }
    }//GEN-LAST:event_btnInteractionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        txtVariable.setText("");
        txtRestriction.setText("");
        txtInteraction.setText("");
        
        tblSimplex.setModel(model);
        model.setColumnCount(0);
        model.setRowCount(0);
        
        tblFinal.setModel(modelSolution);
        modelSolution.setColumnCount(0);
        modelSolution.setRowCount(0);
    }//GEN-LAST:event_btnCleanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnInteraction;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSolution;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblFinal;
    private javax.swing.JTable tblSimplex;
    private javax.swing.JTextField txtInteraction;
    private javax.swing.JTextField txtRestriction;
    private javax.swing.JTextField txtVariable;
    // End of variables declaration//GEN-END:variables

    public int columnPivot() {
        int pos = 0;
        double aux = Matrix[restrictions][0];
        for (int i = 1; i < restrictions + variables; i++) {
            if (aux > Matrix[restrictions][i]) {
                aux = Matrix[restrictions][i];
                pos = i;
            }
        }
        return pos;
    }

    public int rowPivot() {
        int column = columnPivot();
        double temp = 0, razon = Matrix[0][variables + restrictions] / Matrix[0][column];
        int pos = 0;
        for (int i = 1; i < restrictions; i++) {
            if (Matrix[i][column] != 0) {
                temp = Matrix[i][variables + restrictions] / Matrix[i][column];
                if (razon > temp && temp >= 0) {
                    razon = temp;
                    pos = i;
                }
            }
        }
        return pos;
    }

    public void newTable(int Fila, int Columna) {
        double pivot = Matrix[Fila][Columna], temp = 0;//--
        for (int i = 0; i < restrictions + variables + 1; i++) {
            Matrix[Fila][i] = Matrix[Fila][i] / pivot;
        }
        for (int i = 0; i < restrictions + 1; i++) {
            temp = Matrix[i][Columna];
            for (int j = 0; j < variables + restrictions + 1; j++) {
                if (i != Fila) {
                    Matrix[i][j] = Matrix[i][j] - temp * Matrix[Fila][j];
                } else {
                    break;
                }
            }
        }
    }

    public boolean checkResult() {
        boolean result = true;
        for (int i = 0; i < restrictions + variables; i++) {
            if (Matrix[restrictions][i] < 0) {
                result = false;
                break;
            }
        }
        return result;
    }

} // End
